const { readFileSync } = require("fs");
const path = require("path");
const { makeExecutableSchema } = require("graphql-tools");
const resolvers = require("./resolvers").default;

export const schemaFile = path.resolve("schema.graphql");

const baseSchema = `
# Auto-generated by bin/generate-schema
# DO NOT EDIT MANUALLY, ALL CHANGES WILL BE OVERWRITTEN

interface Node {
    id: ID!
}

type Message implements Node {
  id: ID!,
  value: String!
}

type Query {
  messages(): [Message],
}
`;

export function loadSchemaFile() {
  return readFileSync(schemaFile).toString();
}

export function loadSchema() {
  return makeExecutableSchema({
    typeDefs: loadSchemaFile(),
    resolvers,
    logger: console
  });
}